include(${CMAKE_CURRENT_LIST_DIR}/src/common/eebus_data/eebus_data_sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/src/common/eebus_date_time/eebus_date_time_sources.cmake)

set(SOURCES
  src/cli/eebus_cli.c
  src/cli/eebus_cli_cs_lp.c
  src/cli/eebus_cli_eg_lp.c
  src/cli/eebus_cli_ma_mpc.c
  src/cli/eebus_cli_mu_mpc.c
  src/cli/eebus_cli_ma_mgcp.c
  src/cli/eebus_cli_gcp_mgcp.c
  src/cli/eebus_cli_remote_arg.c
  src/common/debug.c
  src/common/eebus_device_info.c
  src/common/eebus_math/eebus_math.c
  src/common/json_impl_cjson.c
  src/common/message_buffer.c
  src/common/service_details.c
  src/common/string_lut.c
  src/common/string_util.c
  src/common/uint64_lut.c
  src/common/vector.c
  src/common/entity_address_list.c
  src/common/eebus_bool/eebus_bool.c
  src/service/service/eebus_service_config.c
  src/service/service/eebus_service.c
  src/ship/mdns/mdns_entry.c
  src/ship/mdns/mdns_debug.c
  src/ship/ship_connection/ship_connection.c
  src/ship/ship_connection/ship_connection_debug.c
  src/ship/ship_connection/ship_message.c
  src/ship/ship_connection/ship_message_deserialize.c
  src/ship/ship_connection/ship_message_serialize.c
  src/ship/ship_connection/client.c
  src/ship/ship_connection/server.c
  src/ship/ship_node/node_connection.c
  src/ship/ship_node/node_connection_container.c
  src/ship/ship_node/ship_node.c
  src/ship/websocket/websocket.c
  src/ship/websocket/websocket_client_creator.c
  src/ship/websocket/websocket_server_creator.c
  src/ship/websocket/websocket_client.c
  src/ship/websocket/websocket_server.c
  src/ship/websocket/http_server.c
  src/ship/websocket/websocket_debug.c
  src/spine/binding/binding_manager.c
  src/spine/device/data_reader.c
  src/spine/device/device_local.c
  src/spine/device/device_remote.c
  src/spine/device/device.c
  src/spine/device/sender.c
  src/spine/entity/entity_local.c
  src/spine/entity/entity_remote.c
  src/spine/entity/entity.c
  src/spine/events/events.c
  src/spine/feature/feature_address_container.c
  src/spine/feature/feature_local.c
  src/spine/feature/feature_remote.c
  src/spine/feature/feature.c
  src/spine/feature/feature_functions.c
  src/spine/feature/operations.c
  src/spine/feature/pending_reply.c
  src/spine/feature/pending_reply_container.c
  src/spine/feature/pending_result.c
  src/spine/feature/pending_result_container.c
  src/spine/feature/pending_write_request.c
  src/spine/feature/pending_write_request_container.c
  src/spine/feature_link/feature_link.c
  src/spine/feature_link/feature_link_container.c
  src/spine/function/function.c
  src/spine/heartbeat/heartbeat_manager.c
  src/spine/model/absolute_or_relative_time.c
  src/spine/model/binding_management_types.c
  src/spine/model/cmd.c
  src/spine/model/datagram.c
  src/spine/model/device_configuration_types.c
  src/spine/model/electrical_connection_types.c
  src/spine/model/entity_types.c
  src/spine/model/feature_types.c
  src/spine/model/filter.c
  src/spine/model/function_types.c
  src/spine/model/loadcontrol_types.c
  src/spine/model/measurement_types.c
  src/spine/model/model.c
  src/spine/model/node_management_types.c
  src/spine/model/possible_operations_types.c
  src/spine/model/specification_version.c
  src/spine/model/subscription_management_types.c
  src/spine/model/usecase_information_types.c
  src/spine/node_management/node_management.c
  src/spine/node_management/node_management_binding.c
  src/spine/node_management/node_management_destination_list.c
  src/spine/node_management/node_management_detailed_discovery.c
  src/spine/node_management/node_management_remote.c
  src/spine/node_management/node_management_subscription.c
  src/spine/node_management/node_management_usecase.c
  src/spine/subscription/subscription_manager.c
  src/use_case/actor/common/eebus_measurement_base.c
  src/use_case/actor/common/eebus_monitor_base.c
  src/use_case/actor/common/eebus_monitor_container.c
  src/use_case/actor/common/eebus_monitor_features.c
  src/use_case/actor/cs/lpc/cs_lpc.c
  src/use_case/actor/cs/lpp/cs_lpp.c
  src/use_case/actor/cs/cs_lp_events.c
  src/use_case/actor/cs/cs_lp_public.c
  src/use_case/actor/cs/cs_lp.c
  src/use_case/actor/eg/lpc/eg_lpc.c
  src/use_case/actor/eg/lpp/eg_lpp.c
  src/use_case/actor/eg/eg_lp_events.c
  src/use_case/actor/eg/eg_lp_public.c
  src/use_case/actor/eg/eg_lp.c
  src/use_case/actor/ma/ma_events.c
  src/use_case/actor/ma/ma_measurement_base.c
  src/use_case/actor/ma/mpc/ma_mpc.c
  src/use_case/actor/ma/mpc/ma_mpc_events.c
  src/use_case/actor/ma/mpc/ma_mpc_measurement.c
  src/use_case/actor/ma/mpc/ma_mpc_public.c
  src/use_case/actor/mu/mpc/mu_mpc.c
  src/use_case/actor/mu/mpc/mu_mpc_events.c
  src/use_case/actor/mu/mpc/mu_mpc_measurement.c
  src/use_case/actor/mu/mpc/mu_mpc_monitor.c
  src/use_case/actor/mu/mpc/mu_mpc_public.c
  src/use_case/actor/ma/mgcp/ma_mgcp.c
  src/use_case/actor/ma/mgcp/ma_mgcp_events.c
  src/use_case/actor/ma/mgcp/ma_mgcp_measurement.c
  src/use_case/actor/ma/mgcp/ma_mgcp_public.c
  src/use_case/actor/gcp/mgcp/gcp_mgcp.c
  src/use_case/actor/gcp/mgcp/gcp_mgcp_measurement.c
  src/use_case/actor/gcp/mgcp/gcp_mgcp_monitor.c
  src/use_case/actor/gcp/mgcp/gcp_mgcp_public.c
  src/use_case/model/load_limit_types.c
  src/use_case/model/mgcp_types.c
  src/use_case/model/mpc_types.c
  src/use_case/model/scaled_value.c
  src/use_case/specialization/device_configuration/device_configuration_client.c
  src/use_case/specialization/device_configuration/device_configuration_common.c
  src/use_case/specialization/device_configuration/device_configuration_server.c
  src/use_case/specialization/device_diagnosis/device_diagnosis_client.c
  src/use_case/specialization/device_diagnosis/device_diagnosis_common.c
  src/use_case/specialization/electrical_connection/electrical_connection_client.c
  src/use_case/specialization/electrical_connection/electrical_connection_common.c
  src/use_case/specialization/electrical_connection/electrical_connection_server.c
  src/use_case/specialization/feature_info_client.c
  src/use_case/specialization/feature_info_server.c
  src/use_case/specialization/helper.c
  src/use_case/specialization/load_control/load_control_client.c
  src/use_case/specialization/load_control/load_control_common.c
  src/use_case/specialization/load_control/load_control_server.c
  src/use_case/specialization/measurement/measurement_client.c
  src/use_case/specialization/measurement/measurement_common.c
  src/use_case/specialization/measurement/measurement_server.c
  src/use_case/use_case.c
)

list(APPEND SOURCES ${EEBUS_DATE_TIME_SOURCES})
list(APPEND SOURCES ${EEBUS_DATA_SOURCES})

set(HEADERS
  src/cli/eebus_cli.h
  src/cli/eebus_cli_cs_lp.h
  src/cli/eebus_cli_eg_lp.h
  src/cli/eebus_cli_handler_interface.h
  src/cli/eebus_cli_interface.h
  src/cli/eebus_cli_ma_mpc.h
  src/cli/eebus_cli_mu_mpc.h
  src/cli/eebus_cli_ma_mgcp.h
  src/cli/eebus_cli_gcp_mgcp.h
  src/cli/eebus_cli_remote_arg.h
  src/common/api/eebus_mutex_interface.h
  src/common/api/eebus_queue_interface.h
  src/common/api/eebus_timer_interface.h
  src/common/array_util.h
  src/common/debug.h
  src/common/eebus_device_info.h
  src/common/eebus_assert.h
  src/common/eebus_timer/eebus_timer.h
  src/common/eebus_errors.h
  src/common/eebus_malloc.h
  src/common/json.h
  src/common/message_buffer.h
  src/common/eebus_arguments.h
  src/common/eebus_bool/eebus_bool.h
  src/common/eebus_math/eebus_math.h
  src/common/eebus_mutex/eebus_mutex.h
  src/common/eebus_queue/eebus_queue.h
  src/common/eebus_thread/eebus_thread.h
  src/common/service_details.h
  src/common/string_lut.h
  src/common/string_util.h
  src/common/struct_util.h
  src/common/uint64_lut.h
  src/common/vector.h
  src/common/entity_address_list.h
  src/service/api/eebus_service_config.h
  src/service/api/eebus_service_interface.h
  src/service/api/service_reader_interface.h
  src/service/service/eebus_service.h
  src/ship/api/connection_state.h
  src/ship/api/data_reader_interface.h
  src/ship/api/data_writer_interface.h
  src/ship/api/info_provider_interface.h
  src/ship/api/mdns_entry.h
  src/ship/api/ship_mdns_interface.h
  src/ship/api/ship_connection_interface.h
  src/ship/api/ship_message.h
  src/ship/api/ship_node_interface.h
  src/ship/api/ship_node_reader_interface.h
  src/ship/api/tls_certificate_interface.h
  src/ship/api/websocket_creator_interface.h
  src/ship/api/http_server_interface.h
  src/ship/api/node_connection_container_interface.h
  src/ship/api/node_connection_interface.h
  src/ship/api/websocket_interface.h
  src/ship/mdns/ship_mdns.h
  src/ship/model/model.h
  src/ship/model/types.h
  src/ship/ship_node/node_connection.h
  src/ship/ship_node/node_connection_container.h
  src/ship/ship_node/ship_node.h
  src/ship/ship_node/ship_node_internal.h
  src/ship/ship_connection/ship_connection.h
  src/ship/ship_connection/ship_connection_debug.h
  src/ship/ship_connection/ship_connection_internal.h
  src/ship/ship_connection/ship_message_deserialize.h
  src/ship/ship_connection/ship_message_serialize.h
  src/ship/ship_connection/client.h
  src/ship/ship_connection/server.h
  src/ship/ship_connection/types.h
  src/ship/websocket/websocket.h
  src/ship/websocket/websocket_client.h
  src/ship/websocket/websocket_internal.h
  src/ship/websocket/websocket_server.h
  src/ship/websocket/http_server.h
  src/ship/websocket/websocket_client_creator.h
  src/ship/websocket/websocket_server_creator.h
  src/ship/websocket/websocket_debug.h
  src/ship/tls_certificate/tls_certificate.h
  src/spine/api/binding_manager_interface.h
  src/spine/api/device_interface.h
  src/spine/api/device_local_interface.h
  src/spine/api/device_remote_interface.h
  src/spine/api/entity_interface.h
  src/spine/api/entity_local_interface.h
  src/spine/api/entity_remote_interface.h
  src/spine/api/feature_interface.h
  src/spine/api/feature_link.h
  src/spine/api/feature_link_container.h
  src/spine/api/feature_local_interface.h
  src/spine/api/feature_remote_interface.h
  src/spine/api/function_interface.h
  src/spine/api/heartbeat_manager_interface.h
  src/spine/api/message.h
  src/spine/api/operations_interface.h
  src/spine/api/sender_interface.h
  src/spine/api/subscription_manager_interface.h
  src/spine/api/pending_reply_container_interface.h
  src/spine/api/pending_reply_interface.h
  src/spine/api/pending_result_container_interface.h
  src/spine/api/pending_result_interface.h
  src/spine/api/pending_write_request_container_interface.h
  src/spine/api/pending_write_request_interface.h
  src/spine/binding/binding_manager.h
  src/spine/device/device_local.h
  src/spine/device/device_remote.h
  src/spine/device/device.h
  src/spine/device/sender.h
  src/spine/entity/entity_local.h
  src/spine/entity/entity_remote.h
  src/spine/entity/entity.h
  src/spine/events/events.h
  src/spine/feature/feature_address_container.h
  src/spine/feature/feature_local.h
  src/spine/feature/feature_remote.h
  src/spine/feature/feature_remote_internal.h
  src/spine/feature/feature.h
  src/spine/feature/feature_functions.h
  src/spine/feature/operations.h
  src/spine/feature/pending_reply.h
  src/spine/feature/pending_reply_container.h
  src/spine/feature/pending_result.h
  src/spine/feature/pending_result_container.h
  src/spine/feature/pending_write_request.h
  src/spine/feature/pending_write_request_container.h
  src/spine/function/function.h
  src/spine/heartbeat/heartbeat_manager.h
  src/spine/model/actuator_level_types.h
  src/spine/model/actuator_level_types.inc
  src/spine/model/actuator_switch_types.h
  src/spine/model/actuator_switch_types.inc
  src/spine/model/alarm_types.h
  src/spine/model/alarm_types.inc
  src/spine/model/bill_types.h
  src/spine/model/bill_types.inc
  src/spine/model/absolute_or_relative_time.h
  src/spine/model/binding_management_types.h
  src/spine/model/binding_management_types.inc
  src/spine/model/command_frame_types.h
  src/spine/model/command_frame_types.inc
  src/spine/model/common_data_types.h
  src/spine/model/common_data_types.inc
  src/spine/model/data_tunneling_types.h
  src/spine/model/data_tunneling_types.inc
  src/spine/model/cmd.h
  src/spine/model/datagram.h
  src/spine/model/datagram_internal.h
  src/spine/model/datagram.inc
  src/spine/model/device_classification_types.h
  src/spine/model/device_classification_types.inc
  src/spine/model/device_configuration_types.h
  src/spine/model/device_configuration_types.inc
  src/spine/model/device_diagnosis_types.h
  src/spine/model/device_diagnosis_types.inc
  src/spine/model/device_types.h
  src/spine/model/device_types.inc
  src/spine/model/direct_control_types.h
  src/spine/model/direct_control_types.inc
  src/spine/model/electrical_connection_types.h
  src/spine/model/electrical_connection_types.inc
  src/spine/model/entity_types.h
  src/spine/model/entity_types.inc
  src/spine/model/error_types.h
  src/spine/model/feature_types.h
  src/spine/model/feature_types.inc
  src/spine/model/filter.h
  src/spine/model/function_types.h
  src/spine/model/function_types.inc
  src/spine/model/hvac_types.h
  src/spine/model/hvac_types.inc
  src/spine/model/identification_types.h
  src/spine/model/identification_types.inc
  src/spine/model/incentive_table_types.h
  src/spine/model/incentive_table_types.inc
  src/spine/model/loadcontrol_types.h
  src/spine/model/loadcontrol_types.inc
  src/spine/model/measurement_types.h
  src/spine/model/measurement_types.inc
  src/spine/model/messaging_types.h
  src/spine/model/messaging_types.inc
  src/spine/model/model.h
  src/spine/model/network_management_types.h
  src/spine/model/network_management_types.inc
  src/spine/model/node_management_types.h
  src/spine/model/node_management_types.inc
  src/spine/model/operating_constraints_types.h
  src/spine/model/operating_constraints_types.inc
  src/spine/model/possible_operations_types.h
  src/spine/model/possible_operations_types.inc
  src/spine/model/power_sequences_types.h
  src/spine/model/power_sequences_types.inc
  src/spine/model/result_types.h
  src/spine/model/result_types.inc
  src/spine/model/sensing_types.h
  src/spine/model/sensing_types.inc
  src/spine/model/setpoint_types.h
  src/spine/model/setpoint_types.inc
  src/spine/model/smart_energy_management_ps_types.h
  src/spine/model/smart_energy_management_ps_types.inc
  src/spine/model/specification_version.h
  src/spine/model/state_information_types.h
  src/spine/model/state_information_types.inc
  src/spine/model/subscription_management_types.h
  src/spine/model/subscription_management_types.inc
  src/spine/model/supply_conditions_types.h
  src/spine/model/supply_conditions_types.inc
  src/spine/model/tariff_information_types.h
  src/spine/model/tariff_information_types.inc
  src/spine/model/task_management_types.h
  src/spine/model/task_management_types.inc
  src/spine/model/threshold_types.h
  src/spine/model/threshold_types.inc
  src/spine/model/time_information_types.h
  src/spine/model/time_information_types.inc
  src/spine/model/time_series_types.h
  src/spine/model/time_series_types.inc
  src/spine/model/timetable_types.h
  src/spine/model/timetable_types.inc
  src/spine/model/usecase_information_types.h
  src/spine/model/usecase_information_types.inc
  src/spine/model/version_types.h
  src/spine/model/version_types.inc
  src/spine/node_management/node_management.h
  src/spine/node_management/node_management_internal.h
  src/spine/node_management/node_management_remote.h
  src/spine/subscription/subscription_manager.h
  src/use_case/api/ma_measurement_interface.h
  src/use_case/api/ma_mpc_listener_interface.h
  src/use_case/api/ma_mgcp_listener_interface.h
  src/use_case/api/eebus_monitor_interface.h
  src/use_case/actor/common/eebus_measurement_base.h
  src/use_case/actor/common/eebus_monitor_base.h
  src/use_case/actor/common/eebus_monitor_container.h
  src/use_case/actor/common/eebus_monitor_features.h
  src/use_case/actor/cs/cs_lp_events.h
  src/use_case/actor/cs/cs_lp_internal.h
  src/use_case/actor/cs/cs_lp.h
  src/use_case/actor/cs/lpc/cs_lpc.h
  src/use_case/actor/cs/lpp/cs_lpp.h
  src/use_case/actor/eg/lpc/eg_lpc.h
  src/use_case/actor/eg/lpp/eg_lpp.h
  src/use_case/actor/eg/eg_lp_events.h
  src/use_case/actor/eg/eg_lp_internal.h
  src/use_case/actor/eg/eg_lp.h
  src/use_case/actor/ma/ma_events.h
  src/use_case/actor/ma/ma_measurement_base.h
  src/use_case/actor/ma/mpc/ma_mpc.h
  src/use_case/actor/ma/mpc/ma_mpc_events.h
  src/use_case/actor/mu/mpc/mu_mpc_events.h
  src/use_case/actor/ma/mpc/ma_mpc_internal.h
  src/use_case/actor/ma/mpc/ma_mpc_measurement.h
  src/use_case/actor/mu/mpc/mu_mpc.h
  src/use_case/actor/mu/mpc/mu_mpc_internal.h
  src/use_case/actor/mu/mpc/mu_mpc_monitor.h
  src/use_case/actor/mu/mpc/mu_mpc_measurement.h
  src/use_case/actor/ma/mgcp/ma_mgcp.h
  src/use_case/actor/ma/mgcp/ma_mgcp_events.h
  src/use_case/actor/ma/mgcp/ma_mgcp_internal.h
  src/use_case/actor/ma/mgcp/ma_mgcp_measurement.h
  src/use_case/actor/gcp/mgcp/gcp_mgcp.h
  src/use_case/actor/gcp/mgcp/gcp_mgcp_internal.h
  src/use_case/actor/gcp/mgcp/gcp_mgcp_measurement.h
  src/use_case/actor/gcp/mgcp/gcp_mgcp_monitor.h
  src/use_case/model/mgcp_types.h
  src/use_case/model/mpc_types.h
  src/use_case/model/scaled_value.h
  src/use_case/model/load_limit_types.h
  src/use_case/specialization/device_configuration/device_configuration_client.h
  src/use_case/specialization/device_configuration/device_configuration_common.h
  src/use_case/specialization/device_configuration/device_configuration_server.h
  src/use_case/specialization/device_diagnosis/device_diagnosis_client.h
  src/use_case/specialization/device_diagnosis/device_diagnosis_common.h
  src/use_case/specialization/electrical_connection/electrical_connection_client.h
  src/use_case/specialization/electrical_connection/electrical_connection_common.h
  src/use_case/specialization/electrical_connection/electrical_connection_server.h
  src/use_case/specialization/feature_info_client.h
  src/use_case/specialization/feature_info_server.h
  src/use_case/specialization/helper.h
  src/use_case/specialization/load_control/load_control_client.h
  src/use_case/specialization/load_control/load_control_common.h
  src/use_case/specialization/load_control/load_control_server.h
  src/use_case/specialization/measurement/measurement_client.h
  src/use_case/specialization/measurement/measurement_common.h
  src/use_case/specialization/measurement/measurement_server.h
  src/use_case/use_case.h
)

list(APPEND HEADERS ${EEBUS_DATE_TIME_HEADERS})
list(APPEND HEADERS ${EEBUS_DATA_HEADERS})

if (FREERTOS)
  list(APPEND SOURCES
    src/common/eebus_mutex/eebus_mutex_freertos.c
    src/common/eebus_queue/eebus_queue_freertos.c
    src/common/eebus_timer/eebus_timer_freertos.c
    src/common/eebus_thread/eebus_thread_freertos.c
    src/ship/mdns/ship_mdns_freertos.c
    src/ship/tls_certificate/tls_certificate_mbedtls.c
  )
else()
  list(APPEND SOURCES
    src/common/eebus_mutex/eebus_mutex.c
    src/common/eebus_queue/eebus_queue.c
    src/common/eebus_thread/eebus_thread.c
    src/ship/tls_certificate/tls_certificate.c
  )

  if (NOT APPLE AND NOT WIN32 AND OPTION_MDNS_USE_AVAHI_CLIENT)
    list(APPEND SOURCES
      src/ship/mdns/ship_mdns_avahi.c
    )
  else()
    list(APPEND SOURCES
      src/ship/mdns/ship_mdns_bonjour.c
    )
  endif()

  if(APPLE)
    list(APPEND SOURCES
      src/common/eebus_timer/eebus_timer_apple.c
    )
  elseif(WIN32)
    list(APPEND SOURCES
      src/common/eebus_timer/eebus_timer_windows.c
    )
  else()
    list(APPEND SOURCES
      src/common/eebus_timer/eebus_timer_linux.c
    )
  endif()
endif()
