namespace cs_lpp_test {
namespace send {

static constexpr char electrical_connection_characteristic_notify[] = R"({
  "datagram": [
    {
      "header": [
        {
          "specificationVersion": "1.3.0"
        },
        {
          "addressSource": [
            {
              "device": "d:_n:HeatPump_123456789"
            },
            {
              "entity": [
                1
              ]
            },
            {
              "feature": 5
            }
          ]
        },
        {
          "addressDestination": [
            {
              "device": "d:_n:HEMS_123456789"
            },
            {
              "entity": [
                1
              ]
            },
            {
              "feature": 4
            }
          ]
        },
        {
          "msgCounter": 31
        },
        {
          "cmdClassifier": "notify"
        }
      ]
    },
    {
      "payload": [
        {
          "cmd": [
            [
              {
                "function": "electricalConnectionCharacteristicListData"
              },
              {
                "filter": [
                  [
                    {
                      "cmdControl": [
                        {
                          "partial": []
                        }
                      ]
                    }
                  ]
                ]
              },
              {
                "electricalConnectionCharacteristicListData": [
                  {
                    "electricalConnectionCharacteristicData": [
                      [
                        {
                          "electricalConnectionId": 0
                        },
                        {
                          "parameterId": 0
                        },
                        {
                          "characteristicId": 0
                        },
                        {
                          "value": [
                            {
                              "number": 700
                            },
                            {
                              "scale": 1
                            }
                          ]
                        }
                      ]
                    ]
                  }
                ]
              }
            ]
          ]
        }
      ]
    }
  ]
})";

}  // namespace send

}  // namespace cs_lpp_test
